spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    connection-timeout: 5000

sentry:
  dsn: '' # Sentry DSN
  traces-sample-rate: 1.0

server:
  error:
    whitelabel:
      enabled: true
  port: 9001

xihe:
  user-agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36'
  time-to-live: 43200